[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ejs"]